name: C Project CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Build Tools
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc make

      - name: Build Project
        run: make

      - name: Run Tests
        run: ./my_program
